### ISSUE TITLE
API Tracking issue: index

### ISSUE THREAD

**Issue by bibliotechie** [bibliotechie/antithesis#7]
This is a tracking issue for the Hypothesis API endpoint `GET /` (i.e., a GET request to the API root). Corresponding wiki page: https://github.com/bibliotechie/antithesis/wiki/Hypothesis-API%3A-index

**Comment by mycelian** [comment]
Looks like there's two ways to go about this while we're in the process of implementing these endpoints:
1) Add each endpoint to the JSON response as we implement them, or
2) Add all the endpoints that we plan on implementing for the MVP at once.

**Comment by bibliotechie** [comment]
My guess is adding them one at a time is better. A feature that isn't labeled as supported probably breaks more cleanly that a feature that's said to exist but 404s, from the client perspective.

**Comment by bibliotechie** [comment]
Also, we'll need to decide where the API root is before we do this. I think `/api/` is fine for now. It could lead to a naming collision down the road though, if there are any other APIs implemented, either on our end or upstream.

**Comment by mycelian** [comment]
> Also, we'll need to decide where the API root is before we do this. I think `/api/` is fine for now. It could lead to a naming collision down the road though, if there are any other APIs implemented, either on our end or upstream.

I was thinking `/hypothesis/` or `/hypothesis/api/`. Amusewiki already has an API with `/api/` paths: https://github.com/bibliotechie/antithesis/blob/master/lib/AmuseWikiFarm/Controller/API.pm

**Comment by bibliotechie** [comment]
Ah, naming collision achieved then, preemptively no less... :)
`/hypothesis/` sounds good to me. The only other thing we might want to associate with that name is the client, but I'd rather keep it completely separate.

**Comment by bibliotechie** [comment]
Fixed by #36

Future changes to this endpoint can be tracked separately.
